# region           = "eu-west-2"
label            = "hashicorp.fun"
app              = "terramino"
user             = "circleci-user"
ecs_cluster_name = "ecs-odilo"
elb_name         = "odilo-front-end"
vpc_name         = "ecs-vpc"