version: 2.1

parameters:
  image-tag:
    type: string
    default: "latest"
  workingdir:
    type: string
    default: "."
  aws-accountid:
    type: string
    default: ""
  aws-access-key:
    type: string
    default: $AWS_ACCESS_KEY_ID
  aws-secret-key:
    type: string
    default: $AWS_SECRET_ACCESS_KEY
  aws-region:
    type: string
    default: "eu-west-2"

orbs:
  orb-tools: circleci/orb-tools@10.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd infrastructure/
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars -var="region=${DEFAULT_AWS_REGION}"
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd infrastructure/
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  plan-apply-apps:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init & plan
          command: |
            cd apps/terraform/
            terraform init -input=false
            terraform plan -out tfapply-apps -var-file variables.tfvars -var="region=${DEFAULT_AWS_REGION}"
      - persist_to_workspace:
          root: .
          paths:
            - .            
  
  apply-apps:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd apps/terraform/
            terraform apply -auto-approve tfapply-apps
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-push-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - aws-ecr/build-and-push-image:
          account-url: DEFAULT_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./apps/dotnetapi/src
          region: DEFAULT_AWS_REGION
          repo: dotnetapi
          skip-when-tags-exist: false
          tag: 'latest,${CIRCLE_SHA1}'

  # update-ecr-service:
  #   docker:
  #     - image: 'cimg/python:3.9.1'
  #   steps:
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-region: AWS_DEFAULT_REGION
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #     - aws-ecs/update-task-definition-from-json:
  #         task-definition-json: ./apps/dotnetapi/src/ecs-app-definition.json
  #     - aws-ecs/deploy-service-update:
  #         cluster-name: 'odilo-cluster'
  #         container-image-name-updates: 'container=dotnetapi-service,tag=${CIRCLE_SHA1}'
  #         family: 'dotnetapi-service'

  plan-destroy-apps:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd apps/terraform/
            terraform plan -destroy -out tfdestroy-apps -var-file variables.tfvars -var="region=${DEFAULT_AWS_REGION}"
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy-apps:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd apps/terraform/
            terraform apply -auto-approve tfdestroy-apps
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd infrastructure/
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars -var="region=${DEFAULT_AWS_REGION}"
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd infrastructure/
            terraform apply -auto-approve tfdestroy
  

workflows:
  version: 2.1
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-apply-apps:
          requires:
            - apply
      - apply-apps:
          requires:
            - plan-apply-apps
      - build-push-image:
          requires:
            - apply-apps
      - plan-destroy-apps:
          requires:
            - build-push-image
      - hold-destroy-apps:
          type: approval
          requires:
            - plan-destroy-apps
      - destroy-apps:
          requires:
            - hold-destroy-apps
      - plan-destroy:
          requires:
            - destroy-apps
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
